#!/bin/bash
# Display information for its subdomains

get_info(){
   # Search for dns record type and destination
   dest_rec=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
   echo "$2 $dest_rec" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 2 ]; then
    get_info "$1" "$2"
else    
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        get_info "$1" "$subdomain"
    done
fi

