#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
 frontend  shophub_frontend
        bind *:80
        mode http
        default_backend shophub_backend
backend shophub_backend
        balance roundrobin
	server 358977-web-01  54.236.30.10:80 check
	server 358977-web-02  100.26.136.204:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the haproxy service
sudo service haproxy restart
