#!/usr/bin/env bash
# This Script:
# Create the file /var/run/myscript.pid containing its PID
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGTERM signal
# Displays to infinity and beyond indefinitely
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

while true
do  
    echo 'To infinity and beyond'
    sleep 2
done
