#!/usr/bin/env bash
#displays To infinity and beyond indefinitely, and  between each iteration of the loop, there is a sleep 2
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
