#!/usr/bin/env bash
# Display numbers from 1 to 20 with statement if the number is 4 or 9 or 17
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
            "4") echo "bad luck from China";;
            "9") echo "bad luck from Japan";;
            "17") echo "bad luck from Italy";;
    esac
    ((i++))
done
