#!/usr/bin/env bash
# Display the time for 12hrs and 59 mins
h=0
while [ $h -le 12 ]
do 
    echo "Hour: $h"
    m=1
    while [ $m -le 59 ]
    do
        echo "$m"
        ((m++))
    done
    ((h++))
done
