#!/usr/bin/env bash
# The script should run the whoami command under the user passed as an argument

if [ $# -eq 0 ]; then
  echo "You must pass a user as an argument"
  exit 1
fi

sudo -u "$1" whoami
