#!/usr/bin/env bash
# Configure a web server to run Nginx as the nginx user and  listen on port 8080.

sudo -u nginx service nginx stop
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
